replicaCount: 1

fullnameOverride: go-app

image:
  repository: "edbighead/go-app"
  tag: "1.0"
  pullPolicy: Always

service:
  type: NodePort
  port: 80

resources:
  requests:
    memory: "32Mi"
    cpu: "10m"
  limits:
    memory: "256Mi"
    cpu: "100m"

    