{
 "title": "go-app",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "show tag values with key=version"
   }
  ]
 },
 "panels": [
  {
   "title": "URL",
   "type": "text",
   "description": "url",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "content": "<br><br>\n<h1 style=\"text-align: center;\" markdown=\"1\"><a href=\"https://amweek.laur.work\">amweek.laur.work</h1>\n\n\n"
  },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "response",
     "select": [
      [
       { "params": [ "http_response" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests timeline",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "requests",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "response",
     "query": "SELECT count(\"http_response\") FROM \"response\" WHERE (\"version\" =~ /^$version$/) AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "http_response" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "Response by code",
   "type": "graph",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "200",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "response",
     "query": "SELECT count(\"http_response\") FROM \"response\" \nWHERE $timeFilter AND \nhttp_response=200 AND\n(\"version\" =~ /^$version$/)\nGROUP BY time(30s), \"version\"",
     "select": [
      [
       { "params": [ "http_response" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "500",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "response",
     "query": "SELECT count(\"http_response\") FROM \"response\" \nWHERE $timeFilter AND\nhttp_response=500 AND\n(\"version\" =~ /^$version$/)\nGROUP BY time(30s), \"version\"",
     "select": [
      [
       { "params": [ "http_response" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Percentage by response",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "200",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"http_response\") FROM \"response\" \nWHERE $timeFilter AND \nhttp_response=200 AND\n(\"version\" =~ /^$version$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "500",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"http_response\") FROM \"response\" \nWHERE $timeFilter AND \nhttp_response=500 AND\n(\"version\" =~ /^$version$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "response",
     "query": "SELECT \"http_response\" as r, version as v FROM \"response\" WHERE \n$timeFilter AND\n(\"version\" =~ /^$version$/)\nGROUP BY http_response fill(null)",
     "select": [
      [
       { "params": [ "http_response" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}